import { useMemo,useState } from 'react'; import {createRoot} from 'react-dom/client'; import './styles.css';
type Template={id:string;name:string;description:string;source:string;features:string[]};
const TEMPLATES:Template[]=[
{id:'core',name:'VintelTool Core',description:'Base VintelTool application shell and shared platform components.',source:'DerivFX4/vinteltool',features:['Dashboard','Navigation','Branding']},
{id:'trading-dashboard',name:'Trading Dashboard',description:'Dashboard template built from the existing VintelTool dashboard card system.',source:'src/pages/dashboard',features:['Local','Bot Builder','Quick Bot Builder','Dashboard cards']},
{id:'bot-builder',name:'Bot Builder',description:'Blockly trading workspace already implemented in VintelTool.',source:'src/pages/bot-builder',features:['Blockly','Trading blocks','Workspace','Bot execution']},
{id:'quick-strategy',name:'Quick Strategy',description:'Configuration-driven strategy studio with visible trading parameter blocks.',source:'src/pages/bot-builder/quick-strategy',features:['Trade Parameters','Analysis','Entry Conditions','Sell Conditions','Money Management']},
{id:'analysis',name:'Analysis Tool',description:'VintelTool analysis experience for market and trading workflows.',source:'src/pages/analysis-tool',features:['Analysis','Signals','Market data']},
{id:'charts',name:'Charts',description:'Existing VintelTool chart page and smartcharts integration.',source:'src/pages/chart',features:['Charts','Market view','Smartcharts']},
{id:'tutorials',name:'Tutorials / Course',description:'Existing learning pages that can be enabled per site.',source:'src/pages/tutorials + src/pages/deriv-course.tsx',features:['Tutorials','Deriv Course']}];
const initialSites=[{id:'vinteltool',name:'VintelTool',domain:'www.vinteltool.site',template:'core',status:'Connected'}];
function App(){const[section,setSection]=useState('sites');const[selectedTemplate,setSelectedTemplate]=useState('core');const[siteName,setSiteName]=useState('');const[domain,setDomain]=useState('');const[sites,setSites]=useState(initialSites);const[message,setMessage]=useState('');const[connections,setConnections]=useState<{github?:boolean;vercel?:boolean}>({});const template=useMemo(()=>TEMPLATES.find(t=>t.id===selectedTemplate)??TEMPLATES[0],[selectedTemplate]);
const createSite=()=>{if(!siteName.trim()){setMessage('Enter a site name first.');return;}setSites(p=>[...p,{id:crypto.randomUUID(),name:siteName.trim(),domain:domain.trim()||'Not connected',template:template.id,status:'Draft'}]);setSiteName('');setDomain('');setMessage('Site created as a draft. Publishing will be connected to GitHub and Vercel in the integration layer.');};
return <div className="studio"><aside className="sidebar"><div className="brand"><div className="brandMark">V</div><div><strong>VintelTool</strong><span>Studio</span></div></div><nav>{[['sites','Sites'],['templates','Templates'],['editor','Site Editor'],['branding','Branding'],['features','Features'],['deployments','Deployments'],['settings','Settings']].map(([id,label])=><button className={section===id?'navItem active':'navItem'} onClick={()=>setSection(id)} key={id}>{label}</button>)}</nav><div className="connection"><span className="dot"/> VintelTool source<small>DerivFX4/vinteltool</small></div></aside><main className="main"><header className="topbar"><div><span className="eyebrow">SITE BUILDER</span><h1>{section==='sites'?'Your sites':section[0].toUpperCase()+section.slice(1)}</h1></div><button className="primary" onClick={()=>setSection('editor')}>+ Create site</button></header>
{section==='sites'&&<section><div className="hero"><div><span className="eyebrow">VINTELTOOL TEMPLATE SYSTEM</span><h2>Build sites from the VintelTool platform.</h2><p>Choose an existing VintelTool template, configure the site, then connect publishing to GitHub and Vercel.</p></div><div className="heroStat"><strong>{sites.length}</strong><span>sites</span></div></div><div className="grid">{sites.map(site=><article className="card" key={site.id}><div className="cardTop"><span className="icon">◈</span><span className={site.status==='Connected'?'status connected':'status'}>{site.status}</span></div><h3>{site.name}</h3><p>{site.domain}</p><div className="meta"><span>{TEMPLATES.find(t=>t.id===site.template)?.name}</span><button onClick={()=>{setSection('editor');setSelectedTemplate(site.template)}}>Edit</button></div></article>)}</div></section>}
{section==='templates'&&<section><div className="sectionHead"><h2>VintelTool templates</h2><p>Mapped to real areas of the existing repository.</p></div><div className="templateGrid">{TEMPLATES.map(t=><article className="template" key={t.id} onClick={()=>{setSelectedTemplate(t.id);setSection('editor')}}><div className="templateIcon">▦</div><h3>{t.name}</h3><p>{t.description}</p><code>{t.source}</code><div className="chips">{t.features.map(f=><span key={f}>{f}</span>)}</div></article>)}</div></section>}
{section==='editor'&&<section className="editor"><div className="panel"><span className="eyebrow">CREATE / CONFIGURE</span><h2>New VintelTool site</h2><label>Site name<input value={siteName} onChange={e=>setSiteName(e.target.value)} placeholder="e.g. My Trading Site"/></label><label>Domain<input value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.com"/></label><label>Template<select value={selectedTemplate} onChange={e=>setSelectedTemplate(e.target.value)}>{TEMPLATES.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><button className="primary wide" onClick={createSite}>Create draft site</button>{message&&<p className="message">{message}</p>}</div><div className="preview"><div className="previewBar"><span>Live template preview</span><span className="pill">Draft</span></div><div className="previewBody"><span className="eyebrow">VINTELTOOL</span><h2>{template.name}</h2><p>{template.description}</p><div className="previewBlocks">{template.features.map((f,i)=><div key={f}><b>0{i+1}</b><span>{f}</span></div>)}</div><small>Source: {template.source}</small></div></div></section>}
{section==='branding'&&<Info title="Branding" text="The Studio will expose the existing brand.config.json model: brand name, domain, colors, typography, logo and platform settings."/>}{section==='features'&&<Info title="Features" text="Enable or disable existing VintelTool capabilities per site: Dashboard, Bot Builder, Quick Strategy, Analysis, Charts, Tutorials and Deriv Course."/>}{section==='deployments'&&<Info title="Deployments" text="The deployment layer is reserved for secure server-side GitHub and Vercel integrations. Tokens must never be shipped to browser code."/>}{section==='settings'&&<section className="info"><span className="eyebrow">STUDIO</span><h2>Studio settings</h2><p>GitHub source: DerivFX4/vinteltool. Studio: DerivFX4/Vinteltoolstudio. Credentials stay server-side and are never placed in browser code.</p><div className="integration"><div><b>GitHub</b><span>{connections.github===undefined?'Not checked':connections.github?'Connected':'Needs attention'}</span></div><div><b>Vercel</b><span>{connections.vercel===undefined?'Not checked':connections.vercel?'Connected':'Needs attention'}</span></div></div><button className="primary" style={{marginTop:18}} onClick={checkConnections}>Check integrations</button>{message&&<p className="message">{message}</p>}</section>}</main></div>}
async function checkConnections(){try{const[r1,r2]=await Promise.all([fetch('/api/github-check'),fetch('/api/vercel-check')]);setConnections({github:r1.ok,vercel:r2.ok});setMessage(r1.ok&&r2.ok?'GitHub and Vercel connections are working.':'One or more integrations need attention.')}catch{setMessage('Could not reach the Studio integration API.')}}
function Info({title,text}:{title:string;text:string}){return <section className="info"><span className="eyebrow">STUDIO</span><h2>{title}</h2><p>{text}</p><div className="integration"><div><b>GitHub</b><span>DerivFX4/vinteltool</span></div><div><b>Vercel</b><span>Ready for secure server integration</span></div></div></section>} createRoot(document.getElementById('root')!).render(<App/>);